name: Generate Labels

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/generate-labels.yml'
      - '.github/labels/label-definition.yaml'
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    paths:
      - '.github/workflows/generate-labels.yml'
      - '.github/labels/label-definition.yaml'

jobs:

  labeler:
    name: labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@548a7c3603594ec17c819e1239f281a3b801ab4d # v6.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels/label-definition.yaml
          skip-delete: false
          dry-run: false
